GET http://localhost:5147/todos

###

POST http://localhost:5147/todos
Content-Type: application/json

{
    "id": 1,
    "name": "Another Demo",
    "dueDate": "2025-10-31",
    "isCompleted": false
}

###

GET http://localhost:5147/todos/2

###

DELETE http://localhost:5147/todos/2

###

GET http://localhost:5147/tasks/1
